title: Lessons Learned
author: jygj65536
email: jygj65536@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
# social links
github_username: jygj65536

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
