title: Lessons Learned
author: jygj65536
email: jygj65536@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Things that I learned today.
# social links
github_username: jygj65536

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
